name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run linter
        run: yarn lint

      # - name: Deploy beta build
      #   run: TODO!
